version: "2"
services:
  hands_on_mysql:
    container_name: hands_on_mysql
    build: ./mysql
    image: hands_on/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret2q3
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.16.1.2

  hands_on_ubuntu:
    container_name: hands_on_ubuntu
    privileged: true
    command: /sbin/init
    build: ./ubuntu
    image: hands_on/ubuntu
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - /Users/unamu/Desktop/git/hands_on_ddd:/opt/hands_on_DDD
      - /Users/unamu/Desktop/git/hands_on_laravel_ddd:/var/www/hands_on_Laravel_DDD
    depends_on:
      - hands_on_mysql
      
volumes:
  db:

# hands_on_ubuntuコンテナからhands_on_mysqlコンテナへの接続ipはgetewayのipを利用する
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.1.0/24
         gateway: 172.16.1.1