version: "2"
services:
  mysql:
    container_name: hands_on_mysql
    build: ./mysql
    image: hands_on/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret2q3
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.16.1.2

  ubuntu:
    container_name: hands_on_ubuntu
    privileged: true
    command: /sbin/init
    build: ./ubuntu
    image: hands_on/ubuntu
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - /Users/yonedahiroshi/Desktop/git/hands_on:/opt/hands_on
    depends_on:
      - mysql
      
  php-cli:
    container_name: hands_on_php-cli
    image: hands_on/php-cli
    build: ./ubuntu
    volumes:
      - /Users/yonedahiroshi/Desktop/git/hands_on:/opt/hands_on
      
volumes:
  db:

# ubuntuコンテナからmysqlコンテナへの接続ipはgetewayのipを利用する
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.1.0/24
         gateway: 172.16.1.1